# RDS
spring:
  datasource:
    url: ${SPRING_DATABASE_URL}
    username: admin
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # hibernate
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
openai:
  model: ${OPENAI_MODEL}
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${OPENAI_KEY}